<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_Data_TC_1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5fa6817e-05f5-42ba-8003-cabc5cc2e944</testSuiteGuid>
   <testCaseLink>
      <guid>45710fe8-458d-4ca4-90eb-7dcca61d74cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login with userID standard_user and valid Password</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9aa95075-9a5d-4910-8d24-e684d90815b9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9aa95075-9a5d-4910-8d24-e684d90815b9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>0543b4df-91e5-4570-a0c1-831ab4350b43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9aa95075-9a5d-4910-8d24-e684d90815b9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>2fff1000-a960-4dbc-97a6-50a6389d024f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92ce5168-6380-43e0-b7e1-4d49d35f6f08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login with userID locked_out_user and valid Password</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>52001358-46ea-452d-9add-6938e842ddbd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>52001358-46ea-452d-9add-6938e842ddbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e1634754-ed43-4fe9-a9b4-4581a67a85eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>52001358-46ea-452d-9add-6938e842ddbd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>197d63c9-1e72-47ef-b09b-c7a2f3c11c53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e38e67c-cb7f-4cbc-84d1-0ac887375c6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login with userID performance_glitch_user and valid Password</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b68fd67e-51f3-4ad5-96d4-0513e2f0b5a6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b68fd67e-51f3-4ad5-96d4-0513e2f0b5a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>5f4ce864-89c4-4788-a88b-6327080b9662</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b68fd67e-51f3-4ad5-96d4-0513e2f0b5a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>7c1cb7c4-6688-4098-aee7-18b9a1a01568</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0afc7d5-773d-4641-a274-657ab9a844c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login with userID problem_user and valid Password</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e2299f65-3afc-465d-845c-bf1ad6e1b313</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e2299f65-3afc-465d-845c-bf1ad6e1b313</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>227ac173-81fc-408c-ae26-fcbe3b53405b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e2299f65-3afc-465d-845c-bf1ad6e1b313</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c5ba84bb-7e8f-4ffd-a71c-0b48c1876320</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>baf42c9a-dc02-48c6-8cc9-8a093977cd89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login with userID Valid and Wrong Password</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>40bd4df9-df73-479a-bb1f-f97758f204d2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>40bd4df9-df73-479a-bb1f-f97758f204d2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>ee60b898-f68d-4b1f-a47d-db801f199b74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>40bd4df9-df73-479a-bb1f-f97758f204d2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5e9a3672-1b7f-4abf-b9ef-10b71201d867</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
