<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Cart_Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9cc41051-cda4-426e-8b6b-9bcfb8ef3c6d</testSuiteGuid>
   <testCaseLink>
      <guid>01d48873-72f5-4a77-99b9-dfba9a2684ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/Add to Cart</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6250cafe-bda5-4326-846e-201f03215233</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6250cafe-bda5-4326-846e-201f03215233</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>38445660-a694-499b-bb0e-e40f00ee11de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6250cafe-bda5-4326-846e-201f03215233</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>adf4dcc2-e3b8-4fd0-a1a4-214b3c91574c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea410327-9086-4e64-9c67-041a8cfd1d13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/Detail Item</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c99e1d9f-ced8-426e-94f9-aac143c60c0d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c99e1d9f-ced8-426e-94f9-aac143c60c0d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>44be48b1-41f6-4f3c-a35a-7c29257357c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c99e1d9f-ced8-426e-94f9-aac143c60c0d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>af7f28b0-2b84-497f-9c7c-50796e9eac21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24aca178-cebc-4f24-84ac-700bda529a93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/Filter - 1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b9cb4406-e015-4d38-b655-87a31dcb9dc4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b9cb4406-e015-4d38-b655-87a31dcb9dc4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>5dcba70d-e882-4b3a-9ab3-3859d90208db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b9cb4406-e015-4d38-b655-87a31dcb9dc4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>783e78fd-d5f7-4115-84c6-9abadd94cbb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92faccd4-7d0e-4653-b90d-91639f208f08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/Filter - 2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3db2d936-f127-4516-a881-c527c93d2a26</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3db2d936-f127-4516-a881-c527c93d2a26</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>717502a2-1d74-493d-9356-b9fbbd954324</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3db2d936-f127-4516-a881-c527c93d2a26</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>6e9af7a2-e876-4dc4-8af6-d34559ee148d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19b79f2e-d837-48a3-9e1e-6b9aabf96d5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart/Remove Cart</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>725ebac0-a84a-4562-8e2b-b3c03abceab6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>725ebac0-a84a-4562-8e2b-b3c03abceab6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f0756b28-695e-4195-aec2-c8a9a3b88165</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>725ebac0-a84a-4562-8e2b-b3c03abceab6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b72dc852-d536-46fb-97a9-508084291c54</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
