<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Price (low to high)_inventory_item_img</name>
   <tag></tag>
   <elementGuidId>3597a697-87a6-4750-a450-7f3fe8625089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='item_2_img_link']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.inventory_item_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8ab1f999-fe4b-432a-b5ea-33a2a053f17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sauce Labs Onesie</value>
      <webElementGuid>1d677a4e-f656-4b57-b286-37189b669bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_item_img</value>
      <webElementGuid>8fe471ce-66e1-4b81-808f-7256ca47c530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/red-onesie-1200x1500.2ec615b2.jpg</value>
      <webElementGuid>75870eea-3b79-4a7d-8b94-e3e796891bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_2_img_link&quot;)/img[@class=&quot;inventory_item_img&quot;]</value>
      <webElementGuid>a254dd3f-bd70-4107-ba56-0a68b569f3a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='item_2_img_link']/img</value>
      <webElementGuid>02dcbbad-7bbc-4c1f-9aa9-5f8e3f8472e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sauce Labs Onesie']</value>
      <webElementGuid>9d82d0b9-ee97-4cbf-8f84-85d616bf2bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>f04cc96d-b0f4-4a1b-ac70-da11c450ccb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sauce Labs Onesie' and @src = '/static/media/red-onesie-1200x1500.2ec615b2.jpg']</value>
      <webElementGuid>94087780-7e88-42af-bc1c-76ba9606f0f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
